### ISSUE TITLE
update form_values

### ISSUE THREAD

**Issue by PhillRob** [fulcrumapp/fulcrum-python#15]
Using your wiki example to update from CSV it manage to update the record status and time but not the `form_values`. I seem to be able to update `record` locally but when verifying in browser only the `update_at` value changes. The string includes arabic text. Is there something I am missing? 
```python
from fulcrum import Fulcrum

formIdIssue = 'X' 
apiToken = "X"  
urlBase = 'https://api.fulcrumapp.com/api/v2/'
fulcrum = Fulcrum(key=apiToken)
data = fulcrum.records.search(url_params={'form_id': formIdIssue})['records']

for record in data:
    print(record['form_values']['803d']['choice_values'])
    if ''.join(record['form_values']['803d']['choice_values']) == 'Park - منتزه':
        record['form_values']['803d']['choice_values'] = 'Garden - حديقة'
        #record['form_values']['803d'] = {'choice_values': [Garden - حديقة'],'other_values': []}
        recordUpdated = fulcrum.records.update(record['id'], record)
    else:
        print('Do nothing.')
```

**Comment by JasonSanford** [comment]
When you update the choice_values key it needs to be an array, even if it's a single item. So it would look more like:

`record['form_values']['803d']['choice_values'] = ['Garden - حديقة']`
