### ISSUE TITLE
Forms and Projects

### ISSUE THREAD

**Issue by rwmeier** [fulcrumapp/fulcrum-python#17]
How are projects and forms related?

How can I find out which projects go with which forms?

Also, is there and table schema documentation?

**Comment by JasonSanford** [comment]
Hi. I think your questions are best answered in the general Fulcrum documentation found [here](http://help.fulcrumapp.com/).

As far as projects go [here](http://help.fulcrumapp.com/web-app/what-are-projects) is the page you're looking for.
